default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["GREETING_DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["GREETING_DATABASE_USER"] %>
  password: <%= ENV["GREETING_DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: greeting_development

test:
  <<: *default
  database: greeting_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

